name: Deploy React Native App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps


      - name: Run tests
        run: npm test

      - name: Deploy to AWS EC2
        env:
           HOST: ${{ secrets.AWS_EC2_HOST }}
           USER: ubuntu
           KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
         echo "$KEY" > private_key.pem
         run: |
           echo "$KEY" > private_key.pem
           chmod 600 private_key.pem

           # Add EC2 to known hosts (Fixes "Host key verification failed" issue)
           ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

           # Securely transfer files (excluding unnecessary ones)
           scp -i private_key.pem -r $(ls -A | grep -Ev 'node_modules|.git|.github') $USER@$HOST:~/react-native-notes-app

           # SSH into EC2 and restart the app
           ssh -i private_key.pem $USER@$HOST << 'EOF'
           cd ~/react-native-notes-app
           npm install --legacy-peer-deps
      
           # Stop any existing process
           pkill -f "node"

           # Start the app in the background
           nohup npm start > app.log 2>&1 &
           echo "Deployment successful!"
           EOF
      
