name: Deploy React Native App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Deploy to AWS EC2 using rsync
        env:
          HOST: ${{ secrets.AWS_EC2_HOST }}
          USER: ubuntu
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Set up SSH
          mkdir -p ~/.ssh
          echo "$KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

          # Use rsync to deploy only changed files
          rsync -avz --exclude=".git" --exclude="node_modules" --exclude=".github" . $USER@$HOST:~/react-native-notes-app

          # SSH into EC2 and restart the app
          ssh $USER@$HOST << 'EOF'
            cd ~/react-native-notes-app
            npm install
            nohup npm start > app.log 2>&1 &
            echo "Deployment successful!"
          EOF

